export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";

export const FETCH_ALBUMS_BY_USER_ID = "FETCH_ALBUMS_BY_USER_ID";
export const FETCH_ALBUMS_BY_USER_ID_SUCCESS = "FETCH_ALBUMS_BY_USER_ID_SUCCESS";
export const FETCH_ALBUMS_BY_USER_ID_ERROR = "FETCH_ALBUMS_BY_USER_ID_ERROR";

export const FETCH_PHOTO_BY_ALBUM_ID = "FETCH_PHOTO_BY_ALBUM_ID";
export const FETCH_PHOTO_BY_ALBUM_ID_SUCCESS = "FETCH_PHOTO_BY_ALBUM_ID_SUCCESS";
export const FETCH_PHOTO_BY_ALBUM_ID_ERROR = "FETCH_PHOTO_BY_ALBUM_ID_ERROR";
